language: ruby
sudo: false
cache: bundler
rvm:
- 2.3.1
before_install:
- gem update --system
- gem update --remote bundler
- gem update --remote bundler
before_script:
- git config --global user.name "$(git --no-pager show --no-patch --format='%an')"
- git config --global user.email "$(git --no-pager show --no-patch --format='%ae')"
- date
script:
- bundle exec jekyll build -t
after_success:
- git add -A
- git commit -m "Updated to $(git rev-parse --short $TRAVIS_COMMIT) at $(date -u +'%Y-%m-%d
  %H:%M:%S %Z')"
- git push https://${GH_TOKEN}@github.com/cjeon/cjeon.github.com.git source:master --force
  -v
branches:
  only:
  - source
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: vI0346a5tvlilrcI2ZkmE9/dg9Y4Uxj4EDMe2EYBhiYJ2C+lVoR5h01BEIBkKlRAM42LiXdT/+OibLxQyiSn3OhuO5EUyYjLXn0d/cJLU3itu5rX45pBOQR+7BlaCVOWM38YTJKshvFdEls4Vn+ud5Qs/puUmrh0BfX+lyeGomarcoZYXWxSfUnPu9V0M3C7ltNyVqbVlp/wnSehNLn86zWsWt+DKjeAlp/dJ4MO1XzhqJxGC/WwU2FGllgbhHHjnN7DYAKS1CyXUKvOTzNMYTbU6DCYQ95DNPvMEp+DUKAupcxJYs6Qy8u8HuZEw+hcjsGL3qqKi0whk3rU8gTXbZg7q6X7ZQPA6wy9zVusvqmdWi3YcUo75CBICB1qpUlpz59nGOoA+abCby+q5xDcSY8ng0/TX3Ql/Op5dqHwF14oD1ZK/2hvdtY/m/YoB6yOsMbeU0mZRx7hEoskChNLXAsQPmARjvwW+Pe7+diQqmpidZU5egV9Ax7BucQ/lp78pnzsFhrw7BLWEtC3oh4+lxA9i+DbSejFqYr0euX1VAjhbUYBsMMJ2WOeLeGWpHDieplfG/IjIwrQiQlaihNRY/WOTcLZ66Ef+MyLBQjRai183YX1WMdG7lt5E5dhvkS5dyzis5Ft8X2ORSmj28v5H5MoiDPH5k+56oZVjTSKtR8=
